version: '3.3'

services:
  db:
    image: postgres:15.0
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: mihvs/foodgram:0.6
    restart: always
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/media/
      - ${PWD}/../data:/app/data/
#    command: ["python", "manage.py", "migrate"]
#    command: >
#      bash -c "python manage.py migrate
#      && python manage.py collectstatic --no-input"
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  static_value:
  media_value:
  data:
