# Generated by Django 3.2.16 on 2022-12-07 05:47

from django.db import migrations

INITIAL_TAGS = (
    {'name': 'Завтрак', 'color': '#dce61e', 'slug': 'breakfast'},
    {'name': 'Обед', 'color': '#0abf28', 'slug': 'lunch'},
    {'name': 'Ужин', 'color': '#6b155d', 'slug': 'dinner'},
)

def add_tags(apps, schema_editor):
    Tag = apps.get_model("recipes", "Tag")
    for tag in INITIAL_TAGS:
        new_tag = Tag(**tag)
        new_tag.save()

def remove_tags(apps, schema_editor):
    Tag = apps.get_model("recipes", "Tag")
    for tag in INITIAL_TAGS:
        Tag.objects.get(slug=tag['slug']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
          add_tags,
          remove_tags
        ),
    ]
